import Head from "next/head";
import Link from "next/link";
import React, { ReactNode, useContext } from "react";
import { Store } from "../utils/Store";

interface LayoutProps {
  children: ReactNode;
  title: string;
}

const Layout = ({ children, title }: LayoutProps) => {
  const { state } = useContext(Store);
  const { cart } = state;
  
  return (
    <>
      {" "}
      <Head>
        <title>{title ? title + " - TanieSuple" : "TanieSuple"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between min-h-screen ">
        <header>
          <nav className="flex items-center justify-between h-12 px-4 shadow-md">
            <Link href="/">
              <a className="text-lg font-bold">TanieSuple</a>
            </Link>
            <div>
              <Link href="/cart">
                <a className="p-2">
                  Koszyk
                  <span className="px-2 py-1 ml-1 text-xs font-bold text-white bg-gray-600 rounded-full">
                  {cart.cartItems.length > 0 && (
                    <span className="px-2 py-1 ml-1 text-xs font-bold text-white bg-red-600 rounded-full">
                      {cart.cartItems.reduce((a: number, c: { quantity: number; }) => a + c.quantity, 0)}
                    </span>
                  )}
                  </span>
                </a>
              </Link>

              <Link href="/login">
                <a className="p-2">Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container px-4 m-auto mt-4">{children}</main>
        <footer className="flex items-center justify-center h-10 shadow-inner">
          footer
        </footer>
      </div>
    </>
  );
};

export default Layout;
