import bcrypt from "bcryptjs";

export const brandsArray = ["Universal", "Trec", "Sport Definition", "6-pak"];
export const categoryArray = [
  "Odżywki Białkowe",
  "Spalacze",
  "Przedtreningówka",
  "Kreatyna",
];

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],

  products: [
    {
      id: 1,
      name: "Universal Animal Whey - 2270g",
      slug: "universal-animal-whey",
      category: "Odżywki Białkowe",
      image: "/images/whey/universal-whey.jpg",
      price: 299,
      brand: "Universal",
      rating: 4.5,
      numReviews: 8,
      flavours: ["ciasteczko", "truskawka", "banan"],
      countInStock: 25,
      description:
        "Animal Whey to wysokiej jakości odżywka białkowa, która polecana jest każdemu, kto poszukuje uzupełnienia pełnowartościowego protein. Wytwarzana jest z kilku frakcji białkowych (w tym izolatu oraz koncentratu białek serwatki). Preparat charakteryzuje się znakomitym smakiem i rozpuszczalnością. Dzięki zastosowaniu różnych źródeł białka uzyskano uniwersalny preparat, którego zastosowanie przyczynia się do szybkiego i wydłużonego w czasie uwalniania aminokwasów do krwiobiegu.",
    },
    {
      id: 2,
      name: "Trec Whey 100 - 2275g",
      slug: "trec-whey-100",
      category: "Odżywki Białkowe",
      image: "/images/whey/trec-whey.jpg",
      price: 229,
      brand: "Trec",
      rating: 4.7,
      numReviews: 123,
      flavours: ["kakao, jogurtowy, ciasteczko", "truskawka", "banan"],
      countInStock: 125,
      description:
        "A popular shirtOdżywka białkowa Trec Whey 100 zawiera 100% koncentratu białka serwatki, o stężeniu czystego białka powyżej 80%. WHEY 100 wytwarzany jest w procesie ultrafiltracji, dzięki czemu charakteryzuje się bardzo niską zawartością tłuszczu oraz laktozy. Do produkcji odżywki białkowej WHEY 100 wykorzystano najwyższej jakości koncentrat białek serwatkowych – wysoko oczyszczone i szybkodziałające źródło pełnowartościowych protein.",
    },
    {
      id: 3,
      name: "Sport Definition That's the Whey ISOLATE - 2000-2270g",
      slug: "sport-definition-thats-the-whey",
      category: "Odżywki Białkowe",
      image: "/images/whey/sd-whey.jpg",
      price: 299,
      brand: "Sport Definition",
      rating: 4.5,
      numReviews: 8,
      flavours: ["ciasteczko", "truskawka", "banan"],
      countInStock: 25,
      description:
        "Sport Definition That’s The Whey® ISOLATE. Suplement diety. Zawiera substancje słodzącą. To najwyższej jakości izolat białka serwatkowego, który powstaje w wyniku użycia niskociśnieniowej i niskotemperaturowej mikrofiltracji z przepływem krzyżowym, co pozwala uzyskać najwyższy stopień czystości i koncentracji protein.   Sport Definition That’s The Whey® ISOLATE to produkt stworzony dla Ciebie, jeśli jesteś osobą aktywną fizycznie, ponieważ białko przyczynia się do wzrostu masy mięśniowej i pomaga w jej utrzymaniu oraz wspiera w utrzymaniu zdrowych kości. Warto pamiętać, że metabolizm białek jest ściśle powiązany z zapotrzebowaniem na energię.",
    },
    {
      id: 4,
      name: "6PAK Nutrition Whey Isolate - 1800g",
      slug: "6pak-nutrition-whey-isolate",
      category: "Odżywki Białkowe",
      image: "/images/whey/6-pak-whey.jpg",
      price: 309,
      brand: "6-pak",
      rating: 4.1,
      numReviews: 7,
      flavours: ["ciasteczko", "naturalny", "kakao", "truskawka", "banan"],
      countInStock: 15,
      description:
        "Izolat białka Odżywka białkowa 6PAK Nutrition Whey Isolate. Suplement diety. Zawiera substancję słodzącą. Najwyższej jakości odżywka białkowa na bazie izolatu białka serwatkowego. To idealna odżywka białkowa dla osób wyczynowo zajmujących się sportem, u których wzrasta zapotrzebowanie na białko w diecie, zwłaszcza podczas treningów siłowych, wytrzymałościowych i wydolnościowych. Spróbuj idealną odżywkę białkową z 6PAK Nutrition.",
    },
    {
      id: 5,
      name: "Trec Przedtreningówka S.A.W. Powder - 400g",
      slug: "trec-saw-powder",
      category: "Przedtreningówka",
      image: "/images/pre-workout/saw.jpg",
      price: 299,
      brand: "Trec",
      rating: 4.7,
      numReviews: 36,
      flavours: ["wiśnia", "malina", "cytryna"],
      countInStock: 25,
      description:
        "Trec S.A.W. Powder to ultra-skoncentrowana formuła przedtreningowa dla profesjonalistów. S.A.W. zwiera unikalny kompleks beta alaniny, kofeiny, aktywatorów tlenku azotu oraz kreatyn. S.A.W. poprawia wydolność podczas następujących po sobie krótkich, bardzo intensywnych ćwiczeń fizycznych. Korzystne działanie występuje w przypadku spożywania 3 g kreatyny dziennie.",
    },
    {
      id: 6,
      name: "Sport Definition Fat No More - 120 kaps",
      slug: "sport-definition-fat-no-more",
      category: "Spalacze",
      image: "/images/fatburner/sd-fatburner.jpg",
      price: 299,
      brand: "Sport Definition",
      rating: 4.5,
      numReviews: 8,
      flavours: ["ciasteczko", "truskawka", "banan"],
      countInStock: 25,
      description:
        "Każda porcja Spalacz tłuszczu Fat No More to połączenie L-tyrozyny, ekstraktów roślinnych i kofeiny. To produkt, którego siła drzemie w starannie dobranych składnikach, dlatego warto zwrócić uwagę na działanie jakie wykazuje każdy z nich. ",
    },
    {
      id: 7,
      name: "6PAK Nutrition Pump PAK - 320g",
      slug: "6pak-nutrition-pump-pak",
      category: "Przedtreningówka",
      image: "/images/pre-workout/6-pak-pre.jpg",
      price: 74,
      brand: "6-pak",
      rating: 3.9,
      numReviews: 8,
      flavours: ["wiśnia", "truskawka", "jabłko"],
      countInStock: 25,
      description:
        "6PAK Nutrition Pump PAK będzie idealnym wyborem dla wszystkich sportowców, którzy uwielbiają efekt pompy treningowej. Arginina jest zaliczana do aminokwasów względnie egzogennych. Ma szczególne znaczenie w organizmie człowieka, ponieważ jest substratem w procesie syntezy tlenku azotu. Tlenek azotu wykazuje wpływ na rozszerzenie naczyń krwionośnych, jest też neurotransmiterem (uczestniczy w przewodzeniu nerwowym). Arginina uczestniczy także w syntezie kreatyny, jest jej prekursorem. Cytrulina z kolei jest ważną częścią cyklu mocznikowego i może uczestniczyć w usuwaniu amoniaku. Ponadto cytrulina jest prekursorem L-argininy, która (jak podano wcześniej) jest składową w procesie syntezy tlenku azotu. Tauryna bierze udział w licznych procesach fizjologicznych. Jej działania odbywają się już na poziomie błony komórkowej. Wpływa na stabilizację błon komórkowych, reguluje ciśnienie osmotyczne, wykazuje również działanie antyoksydacyjne, czyli chroni komórki przed wolnymi rodnikami. Tauryna jest również neuroprzekaźnikiem i neuromodulatorem.",
    },
    {
      id: 8,
      name: "Sport Definition PumpKick - 450g",
      slug: "sport-definition-pump-kick",
      category: "Przedtreningówka",
      image: "/images/pre-workout/sd-pre.jpg",
      price: 99,
      brand: "Sport Definition",
      rating: 4.6,
      numReviews: 18,
      flavours: ["jagoda", "truskawka", "owoce leśne"],
      countInStock: 20,
      description:
        "Przedtreningówka Sport Definition PumpKick. Suplement diety. Zawiera substancje słodzące. Zawiera kofeinę (200 mg / porcję); nie zaleca się stosowania u dzieci, kobiet w ciąży i kobiet karmiących piersią. To produkt przedtreningowy, przeznaczony dla sportowców i osób aktywnych fizycznie. Szukasz wsparcia przed intensywnym treningiem? Masz słabszy dzień? Nie pozwól by coś przeszkodziło Ci w pełnej realizacji Twojego planu treningowego! Przedtreningówka Sport Definition PumpKick to może być świetne rozwiązanie! Zobacz co możesz osiągnąć dzięki składnikom zawartym w tej przedtreningówce.",
    },
    {
      id: 9,
      name: "Trec Boogieman - 300g",
      slug: "trec-boogieman",
      category: "Przedtreningówka",
      image: "/images/pre-workout/boogieman.jpg",
      price: 99,
      brand: "Trec",
      rating: 5,
      numReviews: 32,
      flavours: ["metalu", "rdzy", "mokry karton"],
      countInStock: 25,
      description:
        "Trec Boogieman to suplement diety w proszku, który został opatentowany w celu zwiększenia Twoich możliwości treningowych. Jest połączeniem najbardziej skutecznych substancji aktywnych, stosowanych przed treningiem. Skoncentrowana formuła, dzięki której Twój trening będzie jeszcze bardziej wydajny! Skład produktu jest niezwykle bogaty i bardzo rzadko spotykany! Znajdziemy w nim: beta alaninę, jabłczan cytruliny, L-argininę, taurynę, L-tyrozynę, kofeinę bezwodną, kwas alfa-liponowy (ALA), l-teaninę, ekstrakt żeń-szenia koreańskiego, magnez, ekstrakt różeńca górskiego oraz kompleks witamin z grupy B. Takie połączenie może zapewnić zdecydowaną poprawę zdolności wysiłkowych w trakcie treningu!",
    },
    {
      id: 10,
      name: "Universal Creatine Powder - 500g",
      slug: "universal-creatine-powder",
      category: "Kreatyna",
      image: "/images/creatine/universal-creatine.jpg",
      price: 229,
      brand: "Universal",
      rating: 3.2,
      numReviews: 3,
      flavours: ["cytryna", "naturalny"],
      countInStock: 5,
      description:
        "Universal Creatine Powder to kreatyna najwyższej jakości oraz gwarancji czystości składu (certyfikat CreaPure). Kupując tego typu produkt warto wybierać produkty sprawdzone renomowanych producentów – takie jak ten. Nie pozwól by cokolwiek ograniczało Twoje przyrosty tkanki mięśniowej! Jest to także znakomity wybór by przełamać doskwierającą Ci stagnację. Kreatyna jest organicznym związkiem chemicznym, powstającym w procesie przemiany materii. Występuje głównie w komórkach mięśniowych.Pod wpływem enzymu (kinaza kreatynowa) przekształca się w fosfokreatynę, która umożliwia szybsze odbudowywanie ATP (rozpad wysokoenergetycznych wiązań ATP dostarcza energii do maksymalnych, krótkotrwałych skurczów mięśniowych). Wspomaga syntezę białek, poprawia zdolności wysiłkowe organizmu.",
    },
    {
      id: 11,
      name: "Trec CM3 1250 Jabłczan kreatyny - 360 kaps.",
      slug: "trec-cm3-1250",
      category: "Kreatyna",
      image: "/images/creatine/cm3-creatine.jpg",
      price: 139,
      brand: "Trec",
      rating: 4.2,
      numReviews: 39,
      flavours: ["cytryna", "wiśnia", "naturalny"],
      countInStock: 5,
      description:
        "Jabłczan kreatyny Trec CM3 1250 to preparat zawierający krystalicznie czysty Jabłczan Kreatyny w zwiększonej dawce. Jest to wyjątkowo stabilna, odporna na kwaśne środowisko przewodu pokarmowego i bardzo dobrze rozpuszczalna forma kreatyny. W przeciwieństwie do zwykłego monohydratu Jabłczan Kreatyny nie wywołuje typowych efektów ubocznych, a jego stosowanie prowadzi do intensywniejszego wzrostu siły i masy mięśni. CM3 1250 polecany jest jako środek wspomagający uzyskanie szczytowej formy szczególnie w dyscyplinach siłowych i szybkościowo-siłowych.",
    },
    {
      id: 12,
      name: "6PAK Nutrition CREA PAK - 330g",
      slug: "6pak-nutrition-crea-pak",
      category: "Kreatyna",
      image: "/images/creatine/6pak-creatine.jpg",
      price: 79,
      brand: "6-pak",
      rating: 4.2,
      numReviews: 3,
      flavours: ["wiśnia", "naturalny"],
      countInStock: 5,
      description:
        "Podczas wysiłku o wysokiej intensywności do odtwarzania zasobów ATP wykorzystywana jest kreatyna i fosfokreatyna. Ten główny substrat energetyczny w czasie pracy mięśnia transportuje energię, a w trakcie aktywności fizycznej wzrasta zapotrzebowanie na ATP. Autorzy publikacji naukowej analizującej stosowanie kreatyny (która pojawiła się w czasopiśmie Amino Acids w 2011 r.) podają, że zgodnie z różnymi badaniami naukowymi suplementacja monohydratu kreatyny zwiększa stężenie kreatyny i fosfokreatyny w mięśniach o około 15–40%. Dodatkowo wpływa na zwiększenie wydolności beztlenowej ćwiczeń i zwiększenie objętości treningu, co prowadzi do większego przyrostu siły, mocy i masy mięśniowej. Ponadto w publikacji tej podkreślono, że monohydrat kreatyny nie ulega degradacji podczas normalnego trawienia i prawie 99% spożywanego monohydratu kreatyny jest wchłaniane przez mięśnie lub wydalane z moczem.",
    },
    {
      id: 13,
      name: "6PAK Nutrition Creatine Monohydrate - 300g",
      slug: "6pak-nutrition-creatine",
      category: "Kreatyna",
      image: "/images/creatine/6-pak-creatine.jpg",
      price: 69,
      brand: "6-pak",
      rating: 4.2,
      numReviews: 13,
      flavours: ["cytryna", "naturalny"],
      countInStock: 25,
      description:
        "Kreatyna to główny nośnik energii w mięśniach. Poprzez zwiększenie jej optymalnego poziomu w organizmie, zwiększa się również ilość fosfokreatyny, która wpływa na tempo resyntezy ATP, stanowiące źródło energii dla komórek mięśniowych. A jak wiadomo, w trakcie aktywności fizycznej, zapotrzebowanie na energię, a co za tym idzie, na ATP - wzrasta.",
    },
    {
      id: 14,
      name: "Trec ClenBurexin - 180 kaps",
      slug: "trec-clen-burexin",
      category: "Spalacze",
      image: "/images/fatburner/clen-burexin.jpg",
      price: 109,
      brand: "Trec",
      rating: 3.2,
      numReviews: 3,
      flavours: ["cytryna", "naturalny"],
      countInStock: 45,
      description: `Clenburexin jest opracowanym przez amerykańskie laboratorium Natures Value INC światowym bestsellerem przyśpieszającym "pożeranie" tkanki tłuszczowej. Preparat został przygotowany w celu wsparcia organizmu w walce z nadwagą i nadmiarem tkanki tłuszczowej, która to niestety przykrywa nasze pięknie umięśnione ciało. Chciałbyś pozbyć się "garnituru tłuszczowego" i odkryć ciężko wypracowane mięśnie?! Jeśli tak! To ten preparat został przygotowany właśnie dla Ciebie. Po kilkutygodniowym cyklu będziesz zaskoczony efektami. Twoje ciało zamieni się w prawdziwą skałę. Dzięki temu iż formuła Clenburexinu, została oparta na niezwykle silnych i skutecznych substancjach o działaniu: termogenicznym, lipotropowym oraz diuretycznym to z powodzeniem może być również używana jako skuteczny reduktor tłuszczu nie tylko dla osób aktywnych fizycznie, ale także dla ludzi prowadzą siedzący tryb życia i pracy.`,
    },
  ],
  formula:
    "Przestrzegaj dawek zalecanych przez producenta i znajdujących się na ulotce. ",
};

export default data;
